- src/main/java/club/sk1er/hytilities/config/HytilitiesConfig.java
- src/main/java/club/sk1er/hytilities/handlers/chat/restyler/ChatRestyler.java
- src/main/java/club/sk1er/hytilities/handlers/lobby/limbo/LimboLimiter.java
Todo: clean up current code, add user-customizable formatting (https://canary.discordapp.com/channels/411619823445999637/411620457754787841/759616389853478951)
> new: expand upon chat restyler

- src/main/java/club/sk1er/hytilities/Hytilities.java
- src/main/java/club/sk1er/hytilities/config/HytilitiesConfig.java
- src/main/java/club/sk1er/hytilities/handlers/chat/ChatHandler.java
- src/main/java/club/sk1er/hytilities/handlers/chat/connected/ConnectedMessage.java
Hide messages like "Sending to ServerCode..." and "You are currently connected to ServerCode"
This feature may be useful for people who do not want to reveal which server they are in (including Skyblock).
Tests:
Regex - ✅
In-game locally - ✅
On Hypixel - ✅
> new: hide server connection/connected messages

- src/main/java/club/sk1er/hytilities/util/locraw/LocrawInformation.java
- src/main/java/club/sk1er/hytilities/util/locraw/LocrawUtil.java
Just added some documentation into LocrawInformation
> new: document LocrawInformation

- src/main/java/club/sk1er/hytilities/command/HytilitiesCommand.java
- src/main/java/club/sk1er/hytilities/config/HytilitiesConfig.java
- src/main/java/club/sk1er/hytilities/handlers/chat/restyler/ChatRestyler.java
- src/main/java/club/sk1er/hytilities/tweaker/asm/LayerArmorBaseTweaker.java
- Short channel names (Guild > = G > ...)
- Command alias hytils
- Leather armour hider for Capture the wool
[Discord Pinned Suggestion](https://discordapp.com/channels/411619823445999637/411620521382510592/736200190226333767)
>  new: short channel names

- src/main/java/club/sk1er/hytilities/config/HytilitiesConfig.java
- src/main/java/club/sk1er/hytilities/handlers/chat/whitechat/WhiteChat.java
- src/main/java/club/sk1er/hytilities/handlers/language/LanguageData.java
This PR adds in a setting for white chat messages when receiving/sending someone a PM.
> new: create white chat for private messages

- src/main/java/club/sk1er/hytilities/config/HytilitiesConfig.java
- src/main/java/club/sk1er/hytilities/handlers/chat/ChatHandler.java
- src/main/java/club/sk1er/hytilities/handlers/chat/guild/GuildWelcomer.java
- src/main/java/club/sk1er/hytilities/handlers/language/LanguageData.java
- src/main/resources/languages/en.json
> new: welcome new players when they join your guild

- src/main/java/club/sk1er/hytilities/config/HytilitiesConfig.java
- src/main/java/club/sk1er/hytilities/handlers/chat/cleaner/ChatCleaner.java
> change: add examples to config description

- src/main/java/club/sk1er/hytilities/Hytilities.java
- src/main/java/club/sk1er/hytilities/config/HytilitiesConfig.java
- src/main/java/club/sk1er/hytilities/handlers/lobby/mysterybox/MysteryBoxStar.java
Shows mystery box stars in the mystery vault
> new: show stars on mystery box

- src/main/java/club/sk1er/hytilities/handlers/chat/ChatHandler.java
- src/main/java/club/sk1er/hytilities/util/locraw/LocrawUtil.java
> fix: player sending locraw not returning message.

- src/main/java/club/sk1er/hytilities/command/HousingVisitCommand.java
- src/main/java/club/sk1er/hytilities/handlers/lobby/limbo/LimboLimiter.java
also remove tabs I accidentally put in my most recent commit
> fix: resolve limbo limiter increasing fps lock if it's under 15

- src/main/java/club/sk1er/hytilities/config/HytilitiesConfig.java
- src/main/java/club/sk1er/hytilities/handlers/chat/ChatHandler.java
- src/main/java/club/sk1er/hytilities/handlers/chat/modules/blockers/GuildMOTD.java
- src/main/java/club/sk1er/hytilities/handlers/language/LanguageData.java
- src/main/java/club/sk1er/hytilities/handlers/lobby/limbo/LimboLimiter.java
- src/main/resources/hytilities_at.cfg
- src/main/resources/languages/en.json
- hide the guild motd when joining Hypixel
- fix limbo title text not being removed
- compact murder mystery and bedwars respawn messages
> new: hide guild motd

- src/main/java/club/sk1er/hytilities/Hytilities.java
- src/main/java/club/sk1er/hytilities/command/PlayCommand.java
- src/main/java/club/sk1er/hytilities/config/HytilitiesConfig.java
- src/main/java/club/sk1er/hytilities/handlers/lobby/mysterybox/MysteryBoxStar.java
- src/main/java/club/sk1er/hytilities/tweaker/ClassTransformer.java
- src/main/java/club/sk1er/hytilities/tweaker/asm/GuiChatTransformer.java
fix: MysteryBoxStar not rendering on second page of mystery vault
I done a few cleanup
Thanks asbyth for doing the asm.
The play commands url can be changed, since it is currently using my own gist.
> new: autocomplete for /play commands

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Updated to the forgegradle fork and updated gradle wrapper
> fix: resolve forgegradle issues

- src/main/java/club/sk1er/hytilities/config/HytilitiesConfig.java
- src/main/java/club/sk1er/hytilities/handlers/chat/ChatHandler.java
- src/main/java/club/sk1er/hytilities/handlers/chat/modules/blockers/GiftBlocker.java
- src/main/java/club/sk1er/hytilities/handlers/chat/modules/modifiers/DefaultChatRestyler.java
- src/main/java/club/sk1er/hytilities/handlers/language/LanguageData.java
- src/main/resources/languages/en.json
This feature intends to remove the message "They have gifted X presents." from the chat. Though It does not remove the message `PLAYER gifted AMOUNT OF DAYS of RANK to PLAYERGIFTED!`
The translation in French is probably not correct as It was used Google Translate. Thus do not take my word in it.
> new: gifted message blocker

- src/main/java/club/sk1er/hytilities/config/HytilitiesConfig.java
- src/main/java/club/sk1er/hytilities/handlers/chat/modules/modifiers/DefaultChatRestyler.java
- src/main/java/club/sk1er/hytilities/handlers/language/LanguageData.java
- src/main/resources/languages/en.json
> new: add officer restyle

- src/main/java/club/sk1er/hytilities/command/SkyblockVisitCommand.java
I probably did unnecessary stuff but It works fine.
> fix: resolve hvisit doing sbvisit

- README.md
by cleanup I mean I used dropdowns and rephrased some stuff
> change: cleanup readme & add a features list

- src/main/java/club/sk1er/hytilities/config/HytilitiesConfig.java
- src/main/java/club/sk1er/hytilities/handlers/chat/modules/blockers/ChatCleaner.java
> fix: LineBreakerTrim not working on all messages

- src/main/resources/languages/en.json
> fix #84: "The 'Improved Join Message' normally outputs negative numbers and sometimes fails to be sent."

- src/main/java/club/sk1er/hytilities/handlers/chat/modules/modifiers/WhiteChat.java
- src/main/java/club/sk1er/hytilities/handlers/chat/modules/modifiers/WhitePrivateMessages.java
> Fix White Chat and Private Messages overwriting all hover/click events

- src/main/java/club/sk1er/hytilities/handlers/chat/modules/modifiers/DefaultChatRestyler.java
> fix: resolve Short Channel Names overwriting all Click/Hover Events
